spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/delivery}
    username: ${DATASOURCE_USERNAME:local}
    password: ${DATASOURCE_PASSWORD:local}
  liquibase:
    change-log: classpath:db/liquibase-changeLog.yaml
    enabled: true
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 450MB
      max-request-size: 450MB
  minio:
    endpoint: ${DELIVERY_MINIO_URL:http://localhost:9000}
    accessKey: ${DELIVERY_MINIO_URL:minioadmin}
    secretKey: ${DELIVERY_MINIO_URL:minioadmin}
    bucket: ${DELIVERY_MINIO_BUCKET:delivery}
server:
  error:
    include-message: always
jwt:
    secret: ${JWT_SECRET:koi5wesassg28jyui11dvkkm60zx}
    expiration: ${JWT_EXPIRATION:28800000}


